// SPDX-License-Identifier: PMPL-1.0-or-later

//! Panel lifecycle types for eNSAID-aware bot coordination.
//!
//! This module gives the gitbot-fleet awareness of PanLL panels — their
//! structure, lifecycle phases, wiring requirements, and validation rules.
//! Bots use these types to produce panel-specific findings during minting,
//! provisioning, configuration, and wiring.
//!
//! ## Panel Lifecycle
//!
//! A panel moves through phases:
//!
//! ```text
//! Minted → Wired → Configured → Provisioned → Active
//!   ↑         ↑         ↑            ↑           ↑
//! rhodibot  seambot  echidnabot  finishbot    runtime
//! glambot             seambot
//! ```
//!
//! Each phase has validation rules enforced by specific bots.

use serde::{Deserialize, Serialize};
use std::path::PathBuf;

// =============================================================================
// Panel Identity
// =============================================================================

/// Unique panel identifier — PascalCase name matching the ReScript variant.
///
/// Example: "CloudGuard", "ValenceShell", "Minter"
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PanelId(pub String);

impl PanelId {
    /// Create a new panel ID, validating PascalCase format.
    pub fn new(name: &str) -> Result<Self, PanelError> {
        if name.is_empty() {
            return Err(PanelError::InvalidName("Panel name cannot be empty".into()));
        }
        if !name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false) {
            return Err(PanelError::InvalidName(
                "Panel name must start with uppercase (PascalCase)".into(),
            ));
        }
        if !name.chars().all(|c| c.is_alphanumeric()) {
            return Err(PanelError::InvalidName(
                "Panel name must be alphanumeric only".into(),
            ));
        }
        if RESERVED_NAMES.contains(&name) {
            return Err(PanelError::ReservedName(name.into()));
        }
        Ok(Self(name.to_string()))
    }

    /// Get the camelCase form (e.g. "cloudGuard").
    pub fn to_camel_case(&self) -> String {
        if self.0.is_empty() {
            return String::new();
        }
        let mut chars = self.0.chars();
        let first = chars.next().unwrap_or_default().to_lowercase().to_string();
        format!("{}{}", first, chars.collect::<String>())
    }

    /// Get the snake_case form (e.g. "cloud_guard").
    pub fn to_snake_case(&self) -> String {
        let mut result = String::new();
        for (i, ch) in self.0.chars().enumerate() {
            if ch.is_uppercase() {
                if i > 0 {
                    result.push('_');
                }
                result.extend(ch.to_lowercase());
            } else {
                result.push(ch);
            }
        }
        result
    }

    /// Get the raw PascalCase name.
    pub fn name(&self) -> &str {
        &self.0
    }
}

impl std::fmt::Display for PanelId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// Names that cannot be used for panels — they collide with PanLL internals.
pub const RESERVED_NAMES: &[&str] = &[
    "Model", "View", "Update", "Msg", "App", "Main", "Tea", "Panel", "Pane",
    "PaneL", "PaneN", "PaneW", "PanelSwitcher", "Storage", "Connection",
];

// =============================================================================
// Panel Lifecycle Phases
// =============================================================================

/// The lifecycle phase of a panel within the eNSAID environment.
///
/// Panels progress through phases as bots validate them. Each phase
/// has specific requirements that must be met before advancing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum PanelPhase {
    /// Panel files have been generated by the Minter.
    /// Requirements: 4+ ReScript files exist (Model, Engine, Component, Module).
    /// Validated by: rhodibot (structure), glambot (presentation).
    Minted,

    /// Panel is wired into the global TEA loop.
    /// Requirements: PanelSwitcherModel variant, PanelRegistry entry,
    /// Model.res include, Msg.res type + variant, View.res case, Update.res handler.
    /// Validated by: seambot (seam integrity).
    Wired,

    /// Panel is configured with isolation tier, BoJ routing, and clade assignment.
    /// Requirements: Provisioner config entry, isolation tier set, clade A2ML manifest.
    /// Validated by: echidnabot (type safety), seambot (integration contracts).
    Configured,

    /// Panel has passed all release-readiness checks.
    /// Requirements: Tests exist and pass, clade registered, no Error-severity
    /// findings from any bot, documentation present.
    /// Validated by: finishbot (release gate).
    Provisioned,

    /// Panel is running in the eNSAID environment.
    /// This phase is set at runtime, not by bots.
    Active,
}

impl PanelPhase {
    /// Human-readable description of this phase.
    pub fn description(&self) -> &'static str {
        match self {
            PanelPhase::Minted => "Files generated, awaiting wiring",
            PanelPhase::Wired => "TEA loop connected, awaiting configuration",
            PanelPhase::Configured => "Isolation and clade set, awaiting release gate",
            PanelPhase::Provisioned => "Release-ready, awaiting activation",
            PanelPhase::Active => "Running in eNSAID environment",
        }
    }
}

impl std::fmt::Display for PanelPhase {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PanelPhase::Minted => write!(f, "minted"),
            PanelPhase::Wired => write!(f, "wired"),
            PanelPhase::Configured => write!(f, "configured"),
            PanelPhase::Provisioned => write!(f, "provisioned"),
            PanelPhase::Active => write!(f, "active"),
        }
    }
}

// =============================================================================
// Panel Manifest (what a panel IS)
// =============================================================================

/// Complete description of a panel and its current lifecycle state.
///
/// This is the primary data structure that bots examine when validating
/// a panel. It captures both the intended structure (from the minting
/// request) and the actual state (from filesystem inspection).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanelManifest {
    /// Panel identity (PascalCase name).
    pub id: PanelId,
    /// Short name for the panel bar (max ~8 chars).
    pub short_name: String,
    /// One-line description.
    pub description: String,
    /// Icon identifier for the panel bar.
    pub icon: String,
    /// Whether this panel has a Rust/Tauri backend.
    pub has_backend: bool,
    /// Current lifecycle phase.
    pub phase: PanelPhase,
    /// Clade identifier (e.g. "scanner", "builder", "viewer").
    pub clade_id: Option<String>,
    /// Isolation tier assigned by the Provisioner.
    pub isolation: Option<IsolationTier>,
    /// Results of structural wiring checks.
    pub wiring: WiringStatus,
    /// Bot validation results (most recent per bot).
    pub validations: Vec<PanelValidation>,
}

impl PanelManifest {
    /// Create a manifest for a newly minted panel.
    pub fn new_minted(
        id: PanelId,
        short_name: &str,
        description: &str,
        icon: &str,
        has_backend: bool,
    ) -> Self {
        Self {
            id,
            short_name: short_name.to_string(),
            description: description.to_string(),
            icon: icon.to_string(),
            has_backend,
            phase: PanelPhase::Minted,
            clade_id: None,
            isolation: None,
            wiring: WiringStatus::default(),
            validations: Vec::new(),
        }
    }

    /// Check whether all wiring points are connected.
    pub fn is_fully_wired(&self) -> bool {
        self.wiring.is_complete()
    }

    /// Check whether the panel can advance to the next phase.
    pub fn can_advance(&self) -> bool {
        match self.phase {
            PanelPhase::Minted => self.wiring.is_complete(),
            PanelPhase::Wired => self.clade_id.is_some() && self.isolation.is_some(),
            PanelPhase::Configured => {
                // No Error findings from any bot
                !self.validations.iter().any(|v| v.has_errors)
            }
            PanelPhase::Provisioned => true, // Activation is a runtime decision
            PanelPhase::Active => false,      // Terminal phase
        }
    }

    /// Advance the panel to the next lifecycle phase.
    /// Returns Err if advancement conditions are not met.
    pub fn advance(&mut self) -> Result<PanelPhase, PanelError> {
        if !self.can_advance() {
            return Err(PanelError::CannotAdvance {
                panel: self.id.clone(),
                phase: self.phase,
            });
        }
        self.phase = match self.phase {
            PanelPhase::Minted => PanelPhase::Wired,
            PanelPhase::Wired => PanelPhase::Configured,
            PanelPhase::Configured => PanelPhase::Provisioned,
            PanelPhase::Provisioned => PanelPhase::Active,
            PanelPhase::Active => return Err(PanelError::AlreadyActive(self.id.clone())),
        };
        Ok(self.phase)
    }
}

// =============================================================================
// Wiring Status (the 6 connection points)
// =============================================================================

/// Status of the 6 global wiring points that connect a panel to the TEA loop.
///
/// Each field tracks whether the corresponding insertion in the global file
/// has been detected. Seambot populates this by scanning the actual source files.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct WiringStatus {
    /// `src/model/PanelSwitcherModel.res` — `| PanelXxx` variant exists.
    pub panel_switcher_model: WiringCheck,
    /// `src/modules/PanelRegistry.res` — panel metadata entry exists.
    pub panel_registry: WiringCheck,
    /// `src/Model.res` — `include XxxModel` and state field exist.
    pub model_include: WiringCheck,
    /// `src/Msg.res` — message type and routing variant exist.
    pub msg_routing: WiringCheck,
    /// `src/View.res` — `renderActivePanel` case exists.
    pub view_dispatch: WiringCheck,
    /// `src/Update.res` — sub-updater function and routing case exist.
    pub update_handler: WiringCheck,
    /// `src-tauri/src/main.rs` — Rust commands registered (if has_backend).
    /// Set to `Connected` with note "no backend" for frontend-only panels.
    pub rust_registration: WiringCheck,
}

impl WiringStatus {
    /// Check whether all 7 wiring points are connected.
    pub fn is_complete(&self) -> bool {
        self.panel_switcher_model.is_connected()
            && self.panel_registry.is_connected()
            && self.model_include.is_connected()
            && self.msg_routing.is_connected()
            && self.view_dispatch.is_connected()
            && self.update_handler.is_connected()
            && self.rust_registration.is_connected()
    }

    /// Count how many wiring points are connected vs total.
    pub fn score(&self) -> (usize, usize) {
        let checks = [
            &self.panel_switcher_model,
            &self.panel_registry,
            &self.model_include,
            &self.msg_routing,
            &self.view_dispatch,
            &self.update_handler,
            &self.rust_registration,
        ];
        let connected = checks.iter().filter(|c| c.is_connected()).count();
        (connected, checks.len())
    }

    /// Get all disconnected wiring points with their descriptions.
    pub fn disconnected(&self) -> Vec<(&'static str, &'static str)> {
        let mut missing = Vec::new();
        if !self.panel_switcher_model.is_connected() {
            missing.push(("PanelSwitcherModel.res", "Panel ID variant"));
        }
        if !self.panel_registry.is_connected() {
            missing.push(("PanelRegistry.res", "Panel metadata entry"));
        }
        if !self.model_include.is_connected() {
            missing.push(("Model.res", "Include + state field"));
        }
        if !self.msg_routing.is_connected() {
            missing.push(("Msg.res", "Message type + routing variant"));
        }
        if !self.view_dispatch.is_connected() {
            missing.push(("View.res", "renderActivePanel case"));
        }
        if !self.update_handler.is_connected() {
            missing.push(("Update.res", "Sub-updater + routing case"));
        }
        if !self.rust_registration.is_connected() {
            missing.push(("main.rs", "Rust command registration"));
        }
        missing
    }
}

/// Status of a single wiring connection point.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct WiringCheck {
    /// Whether this wiring point is connected.
    pub status: WiringCheckStatus,
    /// File where this wiring point lives.
    pub file: Option<PathBuf>,
    /// Line number where the wiring was found (for diagnostics).
    pub line: Option<usize>,
    /// Optional note (e.g. "no backend needed").
    pub note: Option<String>,
}

impl Default for WiringCheck {
    fn default() -> Self {
        Self {
            status: WiringCheckStatus::Unknown,
            file: None,
            line: None,
            note: None,
        }
    }
}

impl WiringCheck {
    /// Create a connected check with file location.
    pub fn connected(file: PathBuf, line: usize) -> Self {
        Self {
            status: WiringCheckStatus::Connected,
            file: Some(file),
            line: Some(line),
            note: None,
        }
    }

    /// Create a connected check with a note (e.g. "no backend").
    pub fn connected_with_note(note: &str) -> Self {
        Self {
            status: WiringCheckStatus::Connected,
            file: None,
            line: None,
            note: Some(note.to_string()),
        }
    }

    /// Create a disconnected check.
    pub fn disconnected() -> Self {
        Self {
            status: WiringCheckStatus::Disconnected,
            file: None,
            line: None,
            note: None,
        }
    }

    /// Whether this check indicates a connected wiring point.
    pub fn is_connected(&self) -> bool {
        matches!(self.status, WiringCheckStatus::Connected)
    }
}

/// Status of a wiring check.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum WiringCheckStatus {
    /// Not yet checked.
    Unknown,
    /// Wiring point is present and correct.
    Connected,
    /// Wiring point is missing or incorrect.
    Disconnected,
}

// =============================================================================
// Isolation Tiers (from DD-005)
// =============================================================================

/// Panel isolation tier — determines security boundary.
///
/// From Design Decision DD-005: Three-Tier Panel Isolation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "kebab-case")]
pub enum IsolationTier {
    /// In-process Tauri webview. Full trust, hash-verified. Core panels.
    Native,
    /// Alpine + Podman container. Process isolation, network limited.
    StandardPod,
    /// Stapeln + Chainguard image. Full security stack.
    HardenedPod,
}

impl IsolationTier {
    /// Human-readable label.
    pub fn label(&self) -> &'static str {
        match self {
            IsolationTier::Native => "Native (in-process)",
            IsolationTier::StandardPod => "Standard Pod (Podman)",
            IsolationTier::HardenedPod => "Hardened Pod (Stapeln + Chainguard)",
        }
    }
}

// =============================================================================
// Panel Validation (bot results)
// =============================================================================

/// Result of a bot's validation of a panel.
///
/// Each bot produces one of these after checking a panel. The panel
/// manifest accumulates these to track overall readiness.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanelValidation {
    /// Which bot performed the validation.
    pub bot: crate::bot::BotId,
    /// When the validation was performed.
    pub validated_at: chrono::DateTime<chrono::Utc>,
    /// Whether the validation passed (no errors).
    pub passed: bool,
    /// Whether there were Error-severity findings.
    pub has_errors: bool,
    /// Number of findings at each severity.
    pub error_count: usize,
    pub warning_count: usize,
    pub info_count: usize,
    /// Summary message.
    pub summary: String,
}

// =============================================================================
// Panel File Expectations (the 8-file pattern from DD-004)
// =============================================================================

/// The expected file structure for a panel, following DD-004's 8-file pattern.
///
/// Used by rhodibot to verify that all required files exist after minting.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PanelFileExpectation {
    /// Human description of this file's role.
    pub role: String,
    /// Expected path relative to repo root.
    pub path: PathBuf,
    /// Whether this file is required (vs optional).
    pub required: bool,
    /// Whether this file was found.
    pub found: bool,
}

impl PanelFileExpectation {
    /// Generate the expected file list for a panel.
    pub fn expected_files(panel: &PanelId, has_backend: bool) -> Vec<Self> {
        let name = panel.name();
        let snake = panel.to_snake_case();

        let mut files = vec![
            Self {
                role: "Model types".into(),
                path: PathBuf::from(format!("src/model/{}Model.res", name)),
                required: true,
                found: false,
            },
            Self {
                role: "Engine (pure computation)".into(),
                path: PathBuf::from(format!("src/core/{}Engine.res", name)),
                required: true,
                found: false,
            },
            Self {
                role: "Component (view)".into(),
                path: PathBuf::from(format!("src/components/{}.res", name)),
                required: true,
                found: false,
            },
            Self {
                role: "Module registration".into(),
                path: PathBuf::from(format!("src/modules/{}Module.res", name)),
                required: true,
                found: false,
            },
            Self {
                role: "Clade manifest".into(),
                path: PathBuf::from(format!(
                    "panel-clades/clades/{}/{}.a2ml",
                    panel.to_camel_case(),
                    name
                )),
                required: false, // Generated post-mint
                found: false,
            },
            Self {
                role: "Engine tests".into(),
                path: PathBuf::from(format!(
                    "tests/{}_engine_test.js",
                    snake
                )),
                required: false, // Checked by finishbot, not rhodibot
                found: false,
            },
        ];

        if has_backend {
            files.extend([
                Self {
                    role: "Commands (Tauri bridge)".into(),
                    path: PathBuf::from(format!("src/commands/{}Cmd.res", name)),
                    required: true,
                    found: false,
                },
                Self {
                    role: "Rust module".into(),
                    path: PathBuf::from(format!("src-tauri/src/{}/mod.rs", snake)),
                    required: true,
                    found: false,
                },
                Self {
                    role: "Rust types".into(),
                    path: PathBuf::from(format!("src-tauri/src/{}/types.rs", snake)),
                    required: true,
                    found: false,
                },
                Self {
                    role: "Rust commands".into(),
                    path: PathBuf::from(format!("src-tauri/src/{}/commands.rs", snake)),
                    required: true,
                    found: false,
                },
            ]);
        }

        files
    }

    /// Check which files actually exist on disk.
    pub fn check_existence(files: &mut [Self], repo_root: &std::path::Path) {
        for file in files.iter_mut() {
            file.found = repo_root.join(&file.path).exists();
        }
    }

    /// Get files that are required but missing.
    pub fn missing_required(files: &[Self]) -> Vec<&Self> {
        files
            .iter()
            .filter(|f| f.required && !f.found)
            .collect()
    }
}

// =============================================================================
// Panel-Specific Finding Rules
// =============================================================================

/// Rule IDs used by bots when producing panel-related findings.
///
/// These are constants so that rule IDs are consistent across the fleet
/// and can be referenced in fix recipes and learning pipelines.
pub mod rules {
    // --- rhodibot: structure ---
    /// Panel file missing (required file not found).
    pub const PANEL_FILE_MISSING: &str = "PANEL-001";
    /// Panel name violates naming convention.
    pub const PANEL_NAME_INVALID: &str = "PANEL-002";
    /// Panel name conflicts with reserved name.
    pub const PANEL_NAME_RESERVED: &str = "PANEL-003";
    /// SPDX header missing from generated file.
    pub const PANEL_SPDX_MISSING: &str = "PANEL-004";

    // --- glambot: presentation ---
    /// Component missing ARIA labels.
    pub const PANEL_ARIA_MISSING: &str = "PANEL-010";
    /// Component missing keyboard navigation.
    pub const PANEL_KEYBOARD_MISSING: &str = "PANEL-011";
    /// A2ML clade manifest missing or malformed.
    pub const PANEL_CLADE_MISSING: &str = "PANEL-012";
    /// Doc comments missing on exported functions.
    pub const PANEL_DOCS_MISSING: &str = "PANEL-013";

    // --- seambot: wiring ---
    /// PanelSwitcherModel.res variant missing.
    pub const PANEL_WIRING_SWITCHER: &str = "PANEL-020";
    /// PanelRegistry.res entry missing.
    pub const PANEL_WIRING_REGISTRY: &str = "PANEL-021";
    /// Model.res include or state field missing.
    pub const PANEL_WIRING_MODEL: &str = "PANEL-022";
    /// Msg.res message type or routing variant missing.
    pub const PANEL_WIRING_MSG: &str = "PANEL-023";
    /// View.res renderActivePanel case missing.
    pub const PANEL_WIRING_VIEW: &str = "PANEL-024";
    /// Update.res sub-updater or routing case missing.
    pub const PANEL_WIRING_UPDATE: &str = "PANEL-025";
    /// main.rs Rust command registration missing.
    pub const PANEL_WIRING_RUST: &str = "PANEL-026";
    /// Msg type doesn't match Engine's expected variants.
    pub const PANEL_MSG_MISMATCH: &str = "PANEL-027";

    // --- echidnabot: type safety ---
    /// Cmd bindings don't match Rust command signatures.
    pub const PANEL_CMD_MISMATCH: &str = "PANEL-030";
    /// TypeLL coverage missing (no TypeCheckResult handler).
    pub const PANEL_TYPELL_MISSING: &str = "PANEL-031";
    /// BoJ routing configured but cartridge doesn't exist.
    pub const PANEL_BOJ_INVALID: &str = "PANEL-032";

    // --- finishbot: release gate ---
    /// Test file missing for panel engine.
    pub const PANEL_TESTS_MISSING: &str = "PANEL-040";
    /// Tests exist but are failing.
    pub const PANEL_TESTS_FAILING: &str = "PANEL-041";
    /// Panel not registered in clade browser.
    pub const PANEL_CLADE_UNREGISTERED: &str = "PANEL-042";
    /// Panel has unresolved TODOs in generated code.
    pub const PANEL_TODOS_REMAINING: &str = "PANEL-043";
    /// Bot directives file missing for panel.
    pub const PANEL_DIRECTIVES_MISSING: &str = "PANEL-044";
}

// =============================================================================
// Errors
// =============================================================================

/// Errors specific to panel lifecycle operations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum PanelError {
    /// Panel name is invalid (not PascalCase, empty, etc.).
    InvalidName(String),
    /// Panel name is reserved by PanLL internals.
    ReservedName(String),
    /// Panel cannot advance to the next phase (conditions not met).
    CannotAdvance {
        panel: PanelId,
        phase: PanelPhase,
    },
    /// Panel is already in the Active phase.
    AlreadyActive(PanelId),
    /// Panel not found in context.
    NotFound(PanelId),
}

impl std::fmt::Display for PanelError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PanelError::InvalidName(msg) => write!(f, "Invalid panel name: {}", msg),
            PanelError::ReservedName(name) => write!(f, "'{}' is a reserved panel name", name),
            PanelError::CannotAdvance { panel, phase } => {
                write!(f, "Panel '{}' cannot advance from {} phase", panel, phase)
            }
            PanelError::AlreadyActive(panel) => {
                write!(f, "Panel '{}' is already active", panel)
            }
            PanelError::NotFound(panel) => {
                write!(f, "Panel '{}' not found in context", panel)
            }
        }
    }
}

// =============================================================================
// Context Extension: Panel-Aware Methods
// =============================================================================

/// Extension trait for Context to support panel lifecycle operations.
///
/// This allows bots to register panels, track their phases, and query
/// wiring status through the shared context's `data` HashMap.
pub trait PanelContext {
    /// Register a panel manifest in the shared context.
    fn register_panel(&mut self, manifest: PanelManifest);

    /// Get a panel manifest by ID.
    fn get_panel(&self, id: &PanelId) -> Option<PanelManifest>;

    /// Get all registered panel manifests.
    fn all_panels(&self) -> Vec<PanelManifest>;

    /// Update a panel's wiring status.
    fn update_panel_wiring(&mut self, id: &PanelId, wiring: WiringStatus)
        -> Result<(), PanelError>;

    /// Record a bot's validation result for a panel.
    fn record_panel_validation(
        &mut self,
        id: &PanelId,
        validation: PanelValidation,
    ) -> Result<(), PanelError>;

    /// Try to advance a panel to the next phase.
    fn advance_panel(&mut self, id: &PanelId) -> Result<PanelPhase, PanelError>;
}

impl PanelContext for crate::context::Context {
    fn register_panel(&mut self, manifest: PanelManifest) {
        let key = format!("panel:{}", manifest.id);
        if let Ok(value) = serde_json::to_value(&manifest) {
            self.data.insert(key, value);
        }
    }

    fn get_panel(&self, id: &PanelId) -> Option<PanelManifest> {
        let key = format!("panel:{}", id);
        self.data
            .get(&key)
            .and_then(|v| serde_json::from_value(v.clone()).ok())
    }

    fn all_panels(&self) -> Vec<PanelManifest> {
        self.data
            .iter()
            .filter(|(k, _)| k.starts_with("panel:"))
            .filter_map(|(_, v)| serde_json::from_value(v.clone()).ok())
            .collect()
    }

    fn update_panel_wiring(
        &mut self,
        id: &PanelId,
        wiring: WiringStatus,
    ) -> Result<(), PanelError> {
        let key = format!("panel:{}", id);
        let mut manifest: PanelManifest = self
            .data
            .get(&key)
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .ok_or_else(|| PanelError::NotFound(id.clone()))?;

        manifest.wiring = wiring;
        if let Ok(value) = serde_json::to_value(&manifest) {
            self.data.insert(key, value);
        }
        Ok(())
    }

    fn record_panel_validation(
        &mut self,
        id: &PanelId,
        validation: PanelValidation,
    ) -> Result<(), PanelError> {
        let key = format!("panel:{}", id);
        let mut manifest: PanelManifest = self
            .data
            .get(&key)
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .ok_or_else(|| PanelError::NotFound(id.clone()))?;

        // Replace any existing validation from the same bot
        manifest.validations.retain(|v| v.bot != validation.bot);
        manifest.validations.push(validation);

        if let Ok(value) = serde_json::to_value(&manifest) {
            self.data.insert(key, value);
        }
        Ok(())
    }

    fn advance_panel(&mut self, id: &PanelId) -> Result<PanelPhase, PanelError> {
        let key = format!("panel:{}", id);
        let mut manifest: PanelManifest = self
            .data
            .get(&key)
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .ok_or_else(|| PanelError::NotFound(id.clone()))?;

        let new_phase = manifest.advance()?;
        if let Ok(value) = serde_json::to_value(&manifest) {
            self.data.insert(key, value);
        }
        Ok(new_phase)
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_panel_id_valid() {
        assert!(PanelId::new("CloudGuard").is_ok());
        assert!(PanelId::new("MyPanel123").is_ok());
        assert!(PanelId::new("X").is_ok());
    }

    #[test]
    fn test_panel_id_invalid() {
        assert!(PanelId::new("").is_err());
        assert!(PanelId::new("lowercase").is_err());
        assert!(PanelId::new("has-dash").is_err());
        assert!(PanelId::new("has space").is_err());
    }

    #[test]
    fn test_panel_id_reserved() {
        assert!(PanelId::new("Model").is_err());
        assert!(PanelId::new("Msg").is_err());
        assert!(PanelId::new("PaneL").is_err());
    }

    #[test]
    fn test_panel_id_case_conversion() {
        let id = PanelId::new("CloudGuard").unwrap();
        assert_eq!(id.to_camel_case(), "cloudGuard");
        assert_eq!(id.to_snake_case(), "cloud_guard");

        let id2 = PanelId::new("VeriSimDB").unwrap();
        assert_eq!(id2.to_camel_case(), "veriSimDB");
        assert_eq!(id2.to_snake_case(), "veri_sim_d_b");
    }

    #[test]
    fn test_wiring_status_score() {
        let mut ws = WiringStatus::default();
        assert_eq!(ws.score(), (0, 7));
        assert!(!ws.is_complete());

        ws.panel_switcher_model = WiringCheck::connected_with_note("present");
        assert_eq!(ws.score(), (1, 7));
    }

    #[test]
    fn test_wiring_status_complete() {
        let ws = WiringStatus {
            panel_switcher_model: WiringCheck::connected_with_note("ok"),
            panel_registry: WiringCheck::connected_with_note("ok"),
            model_include: WiringCheck::connected_with_note("ok"),
            msg_routing: WiringCheck::connected_with_note("ok"),
            view_dispatch: WiringCheck::connected_with_note("ok"),
            update_handler: WiringCheck::connected_with_note("ok"),
            rust_registration: WiringCheck::connected_with_note("no backend"),
        };
        assert!(ws.is_complete());
        assert_eq!(ws.score(), (7, 7));
        assert!(ws.disconnected().is_empty());
    }

    #[test]
    fn test_panel_manifest_lifecycle() {
        let id = PanelId::new("TestPanel").unwrap();
        let mut manifest = PanelManifest::new_minted(
            id, "Test", "A test panel", "test-icon", false,
        );

        assert_eq!(manifest.phase, PanelPhase::Minted);
        assert!(!manifest.can_advance()); // Wiring not complete

        // Complete wiring
        manifest.wiring = WiringStatus {
            panel_switcher_model: WiringCheck::connected_with_note("ok"),
            panel_registry: WiringCheck::connected_with_note("ok"),
            model_include: WiringCheck::connected_with_note("ok"),
            msg_routing: WiringCheck::connected_with_note("ok"),
            view_dispatch: WiringCheck::connected_with_note("ok"),
            update_handler: WiringCheck::connected_with_note("ok"),
            rust_registration: WiringCheck::connected_with_note("no backend"),
        };

        assert!(manifest.can_advance());
        let next = manifest.advance().unwrap();
        assert_eq!(next, PanelPhase::Wired);
    }

    #[test]
    fn test_panel_file_expectations() {
        let id = PanelId::new("Wharf").unwrap();
        let files = PanelFileExpectation::expected_files(&id, false);
        assert_eq!(files.len(), 6); // 4 required + 2 optional (no backend)

        let files_with_backend = PanelFileExpectation::expected_files(&id, true);
        assert_eq!(files_with_backend.len(), 10); // 6 + 4 Rust files

        let missing = PanelFileExpectation::missing_required(&files);
        assert_eq!(missing.len(), 4); // All required files "missing" (found=false)
    }

    #[test]
    fn test_panel_context_integration() {
        let mut ctx = crate::context::Context::new("panll", "/path/to/panll");
        let id = PanelId::new("Wharf").unwrap();
        let manifest = PanelManifest::new_minted(
            id.clone(), "Wharf", "Container orchestration panel", "ship", true,
        );

        ctx.register_panel(manifest);

        let retrieved = ctx.get_panel(&id).unwrap();
        assert_eq!(retrieved.id, id);
        assert_eq!(retrieved.phase, PanelPhase::Minted);
        assert!(!retrieved.is_fully_wired());

        let all = ctx.all_panels();
        assert_eq!(all.len(), 1);
    }

    #[test]
    fn test_disconnected_reports_missing() {
        let ws = WiringStatus {
            panel_switcher_model: WiringCheck::connected_with_note("ok"),
            panel_registry: WiringCheck::disconnected(),
            model_include: WiringCheck::connected_with_note("ok"),
            msg_routing: WiringCheck::disconnected(),
            view_dispatch: WiringCheck::connected_with_note("ok"),
            update_handler: WiringCheck::connected_with_note("ok"),
            rust_registration: WiringCheck::connected_with_note("ok"),
        };
        let missing = ws.disconnected();
        assert_eq!(missing.len(), 2);
        assert_eq!(missing[0].0, "PanelRegistry.res");
        assert_eq!(missing[1].0, "Msg.res");
    }
}
