// SPDX-License-Identifier: MPL-2.0

//! GitHub App authentication: RS256 app JWTs and installation tokens.
//!
//! # Why this module exists
//!
//! Until this landed, the only credential the bot understood was a
//! `GITHUB_TOKEN` environment variable — a single token, scoped to a single
//! repository, which is not how a GitHub App works. An App authenticates in two
//! steps:
//!
//! 1. Sign a short-lived JWT (RS256) with the App's private key, and present it
//!    as `iss` = the App ID. This is the *app* identity.
//! 2. Exchange that JWT for an *installation* token, which is what actually
//!    carries permissions on repositories the App is installed on. Those tokens
//!    expire after an hour, so they are cached and refreshed here.
//!
//! # Security considerations
//!
//! - The private key is parsed once at start-up into an opaque key pair and is
//!   never logged, serialised, or included in an error message.
//! - Signing uses `ring`, which is already in the dependency tree via rustls.
//!   No hand-rolled bignum arithmetic is involved.
//! - Installation tokens are held in memory with their expiry and are refreshed
//!   five minutes early, so a request never races the expiry.
//! - Errors carry a status code and a context string, never a credential.

use std::sync::Mutex;

use anyhow::{Context, Result, anyhow};
use base64::Engine;
use base64::engine::general_purpose::{STANDARD, URL_SAFE_NO_PAD};
use chrono::{DateTime, Duration as ChronoDuration, Utc};
use ring::rand::SystemRandom;
use ring::signature::{RSA_PKCS1_SHA256, RsaKeyPair};
use serde::Deserialize;

/// User agent presented to the GitHub API.
pub const USER_AGENT: &str = "rhodibot";

/// Longest JWT lifetime GitHub accepts, minus a margin. GitHub rejects `exp`
/// more than ten minutes in the future.
const JWT_LIFETIME_SECS: i64 = 540;

/// Backdate `iat` to tolerate clock drift between us and GitHub.
const JWT_BACKDATE_SECS: i64 = 60;

/// Refresh an installation token this long before it expires.
const TOKEN_REFRESH_MARGIN_SECS: i64 = 300;

/// A cached installation token and the moment it stops being usable.
#[derive(Clone)]
struct CachedToken {
    installation_id: u64,
    token: String,
    expires_at: DateTime<Utc>,
}

#[derive(Deserialize)]
struct InstallationTokenResponse {
    token: String,
    expires_at: DateTime<Utc>,
}

#[derive(Deserialize)]
struct InstallationResponse {
    id: u64,
}

/// GitHub App authentication.
///
/// Holds the parsed private key and a cache of installation tokens. Cheap to
/// clone-sharing: wrap in an `Arc` and share the client between handlers.
pub struct AppAuth {
    app_id: u64,
    key_pair: RsaKeyPair,
    client: reqwest::Client,
    api_url: String,
    cached: Mutex<Option<CachedToken>>,
}

impl AppAuth {
    /// Build from an App ID and a PEM private key.
    ///
    /// Accepts both PEM forms GitHub hands out: PKCS#1 (`BEGIN RSA PRIVATE
    /// KEY`) and PKCS#8 (`BEGIN PRIVATE KEY`). Historically GitHub App keys are
    /// PKCS#1, while anything generated by recent tooling is usually PKCS#8;
    /// accepting both avoids a deployment failing on a key format detail.
    pub fn new(app_id: u64, private_key_pem: &str, api_url: &str) -> Result<Self> {
        let der = pkcs8_der_from_pem(private_key_pem)?;
        let key_pair = RsaKeyPair::from_pkcs8(&der)
            .map_err(|_| anyhow!("the private key is not a usable RSA key"))?;

        Ok(Self {
            app_id,
            key_pair,
            client: reqwest::Client::new(),
            api_url: api_url.trim_end_matches('/').to_string(),
            cached: Mutex::new(None),
        })
    }

    /// The App ID this instance authenticates as.
    pub fn app_id(&self) -> u64 {
        self.app_id
    }

    /// A freshly signed app JWT. Exposed for the `--dump-jwt` style diagnostic
    /// path and for tests; callers normally want [`Self::installation_token`].
    pub fn app_jwt(&self) -> Result<String> {
        sign_app_jwt(self.app_id, &self.key_pair, Utc::now())
    }

    /// Find the installation ID for a repository, using the app JWT.
    ///
    /// This is how a webhook delivery learns which installation to act as,
    /// since the payload's `installation.id` is not always present.
    pub async fn installation_for_repository(&self, owner: &str, repo: &str) -> Result<u64> {
        let jwt = self.app_jwt()?;
        let url = format!("{}/repos/{owner}/{repo}/installation", self.api_url);
        let response = self
            .client
            .get(&url)
            .bearer_auth(jwt)
            .header("Accept", "application/vnd.github+json")
            .header("User-Agent", USER_AGENT)
            .header("X-GitHub-Api-Version", "2022-11-28")
            .send()
            .await
            .context("looking up the installation for a repository")?;

        let status = response.status();
        if !status.is_success() {
            return Err(anyhow!("installation lookup failed with HTTP {status}"));
        }

        let installation: InstallationResponse = response
            .json()
            .await
            .context("parsing the installation lookup response")?;
        Ok(installation.id)
    }

    /// An installation token for the given installation, from cache when it is
    /// still comfortably valid.
    pub async fn installation_token(&self, installation_id: u64) -> Result<String> {
        if let Some(token) = self.cached_token(installation_id) {
            return Ok(token);
        }

        let jwt = self.app_jwt()?;
        let url = format!(
            "{}/app/installations/{installation_id}/access_tokens",
            self.api_url
        );
        let response = self
            .client
            .post(&url)
            .bearer_auth(jwt)
            .header("Accept", "application/vnd.github+json")
            .header("User-Agent", USER_AGENT)
            .header("X-GitHub-Api-Version", "2022-11-28")
            .send()
            .await
            .context("requesting an installation token")?;

        let status = response.status();
        if !status.is_success() {
            return Err(anyhow!(
                "installation token request failed with HTTP {status}"
            ));
        }

        let body: InstallationTokenResponse = response
            .json()
            .await
            .context("parsing the installation token response")?;

        if let Ok(mut cache) = self.cached.lock() {
            *cache = Some(CachedToken {
                installation_id,
                token: body.token.clone(),
                expires_at: body.expires_at,
            });
        }

        Ok(body.token)
    }

    fn cached_token(&self, installation_id: u64) -> Option<String> {
        let cache = self.cached.lock().ok()?;
        let entry = cache.as_ref()?;
        if entry.installation_id != installation_id {
            return None;
        }
        let remaining = entry.expires_at.signed_duration_since(Utc::now());
        if remaining <= ChronoDuration::seconds(TOKEN_REFRESH_MARGIN_SECS) {
            return None;
        }
        Some(entry.token.clone())
    }
}

/// Sign a GitHub App JWT: the RS256 half of App authentication.
///
/// `now` is a parameter rather than read from the clock so the lifetimes are
/// testable.
pub fn sign_app_jwt(app_id: u64, key_pair: &RsaKeyPair, now: DateTime<Utc>) -> Result<String> {
    let header = serde_json::json!({ "alg": "RS256", "typ": "JWT" });
    let claims = serde_json::json!({
        "iat": now.timestamp() - JWT_BACKDATE_SECS,
        "exp": now.timestamp() + JWT_LIFETIME_SECS,
        // GitHub accepts either the App ID or the client ID here; the App ID is
        // the one this struct is constructed with.
        "iss": app_id.to_string(),
    });

    let signing_input = format!(
        "{}.{}",
        URL_SAFE_NO_PAD.encode(serde_json::to_vec(&header)?),
        URL_SAFE_NO_PAD.encode(serde_json::to_vec(&claims)?)
    );

    let rng = SystemRandom::new();
    let mut signature = vec![0u8; key_pair.public().modulus_len()];
    key_pair
        .sign(
            &RSA_PKCS1_SHA256,
            &rng,
            signing_input.as_bytes(),
            &mut signature,
        )
        .map_err(|_| anyhow!("signing the app JWT failed"))?;

    Ok(format!(
        "{signing_input}.{}",
        URL_SAFE_NO_PAD.encode(signature)
    ))
}

/// Decode a PEM private key to PKCS#8 DER, converting PKCS#1 if needed.
pub fn pkcs8_der_from_pem(pem: &str) -> Result<Vec<u8>> {
    let (label, body) = split_pem(pem)?;
    let der = STANDARD
        .decode(body.as_bytes())
        .context("the private key PEM body is not valid base64")?;

    match label.as_str() {
        "PRIVATE KEY" => Ok(der),
        "RSA PRIVATE KEY" => Ok(pkcs1_to_pkcs8(&der)),
        other => Err(anyhow!("unsupported private key type: {other}")),
    }
}

/// Split a PEM into its label and its base64 body, ignoring surrounding prose.
fn split_pem(pem: &str) -> Result<(String, String)> {
    let mut label: Option<String> = None;
    let mut body = String::new();

    for line in pem.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("-----END ") {
            break;
        }
        if let Some(rest) = trimmed.strip_prefix("-----BEGIN ") {
            label = Some(rest.trim_end_matches('-').trim().to_string());
            continue;
        }
        if label.is_some() && !trimmed.is_empty() {
            body.push_str(trimmed);
        }
    }

    let label = label.ok_or_else(|| anyhow!("the private key is not PEM (no BEGIN line)"))?;
    if body.is_empty() {
        return Err(anyhow!("the private key PEM has an empty body"));
    }
    Ok((label, body))
}

/// Wrap a PKCS#1 `RSAPrivateKey` in a PKCS#8 `PrivateKeyInfo` envelope.
///
/// `ring` only accepts PKCS#8, and GitHub historically issues PKCS#1, so the
/// envelope is built here rather than pulling in an ASN.1 crate. The output is
/// byte-identical to `openssl pkcs8 -topk8 -nocrypt` for the same key, which is
/// asserted by a test.
fn pkcs1_to_pkcs8(pkcs1: &[u8]) -> Vec<u8> {
    // AlgorithmIdentifier for rsaEncryption with an explicit NULL parameter.
    const RSA_ENCRYPTION: [u8; 15] = [
        0x30, 0x0d, 0x06, 0x09, 0x2a, 0x86, 0x48, 0x86, 0xf7, 0x0d, 0x01, 0x01, 0x01, 0x05, 0x00,
    ];

    // privateKey OCTET STRING wrapping the PKCS#1 structure
    let mut octet = Vec::with_capacity(pkcs1.len() + 6);
    octet.push(0x04);
    octet.extend_from_slice(&der_len(pkcs1.len()));
    octet.extend_from_slice(pkcs1);

    // SEQUENCE { version INTEGER 0, algorithm, privateKey }
    let mut body = Vec::with_capacity(octet.len() + RSA_ENCRYPTION.len() + 3);
    body.extend_from_slice(&[0x02, 0x01, 0x00]);
    body.extend_from_slice(&RSA_ENCRYPTION);
    body.extend_from_slice(&octet);

    let mut out = Vec::with_capacity(body.len() + 6);
    out.push(0x30);
    out.extend_from_slice(&der_len(body.len()));
    out.extend_from_slice(&body);
    out
}

/// DER length encoding: short form below 128, otherwise long form.
fn der_len(len: usize) -> Vec<u8> {
    if len < 0x80 {
        return vec![len as u8];
    }
    let bytes = len.to_be_bytes();
    let first_significant = bytes
        .iter()
        .position(|byte| *byte != 0)
        .unwrap_or(bytes.len() - 1);

    let mut out = Vec::with_capacity(bytes.len() - first_significant + 1);
    out.push(0x80 | (bytes.len() - first_significant) as u8);
    out.extend_from_slice(&bytes[first_significant..]);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use ring::signature::{RSA_PKCS1_2048_8192_SHA256, RsaPublicKeyComponents};

    // A throwaway 2048-bit RSA key, generated for these tests and used for
    // nothing else. It is stored as raw DER rather than PEM so that secret
    // scanners — GitHub's push protection among them — do not have to be taught
    // that this one is inert.
    const TEST_KEY_PKCS1_DER_HEX: &str = concat!(
        "308204a20201000282010100a2bf269b48f86d86a0df534494b0e40685b18d3b",
        "b2d645d275916feaf69ffc54eb16e8219769c315b1a02c0002c259f8e3008169",
        "b38a3045f4f496ef3efbd678dc352515f04d1d64c37be94c25992c239c8b5c2f",
        "568a34fc84cdbce0f055fed42521ad9bb61e29d295beb22f47399bfaed4c3650",
        "29d7a222e3e1803dd0b9f3c70ed8577872929b4f882ae2ffe30b3fdf71dd12a3",
        "8c0df81de8b22f27f24d7f279d3a0389ecbfd5b6bb5b07b919243475e32044ce",
        "1f63e5a115d5a1790fb8205ed31a4c83b47a6b8598bdbf0360edb9e455b7e96f",
        "ab0399a330bf65806d97293efeb3d21e5e353b1eafe3bfaae54c6a3b9cb9aed1",
        "6738c112157da2f65ca971570203010001028201003e4d3fd9c562f906c75206",
        "fde3901e12d31e67cb3948a6dd0d0dda92cfcbea1c960ca45babab9cb792d296",
        "d58038e7998c4916c1a0ae1f91c056dbeb05a901ef2d9998b35fd51d9203f5cd",
        "174df367bed040574f75e91da4a7b05d049d6cc64b6f5587b0ead47c3d35ff15",
        "165d45540d88c71aa9b082f07a3bd38934e0d136dd5a657941ca6ce3f57e5844",
        "82e5ee0fa135ed0439545b777a1d971fe764fa902f8ab6238d40fd95c5403598",
        "afa036170468e1a0042d39897d3cd4037ba166d2eb9d8e653e92c9be31cea023",
        "ba49e6a438d73bdf0b90d8eaa327b674763fdb7b841144e041e2883657998bb2",
        "4eedee8bdb4458ba0ed9118d423385d2aeb693bbc902818100d04248e969a186",
        "88912ec23d435f7289a872a480aa34aa5c55905c801ae176868593de13c954b0",
        "c952a075430fe3a48ca96f78a39c9b91903adc0aec7646c31ec05948806401cf",
        "52faea53ce290a99963604b5842998c13ba35a9f011a57d43ac274e5f801c11d",
        "b47477762fd5b3f2a6e2f386a057730a11e5ffff44c47bf0cf02818100c80df8",
        "a5f75e696b684a8a882e7d77362b641ccc30724058f03989682a56d2c1beef45",
        "0dc47e55c7b608f1ae706a9304a39c9311329bc55ded582f60575b9dd37e7899",
        "cd1494d2f4d18cc37642f974c498ae1d034c0697a663ab3b3b955f0abca5a9a2",
        "64bff35a7b641e3e81518c705bc7e6c117451fd3ba2746c2c8d9fe48f9028180",
        "615238846b4a82761b72806ee4a71bfd5c6c869761f2ce91eba254b7c0d80fed",
        "794aca82f098d52c9fa2406a2068bf22c4a344fb205a4ac1dddfaa732a2a9350",
        "318f07a48817986d2cb88885550491157314ec4660b1f3cb0ce17260af90cfaa",
        "cde896f738caa839061c356cd12f107c109ec110f90cd76dd9cfb1d8cf01245d",
        "0281806deff797c523f60cd768374ef5356fc0ae01bb2d9ee5fa64a5c708b2dc",
        "a98ff276e9e869d37495d145410f078cb1948f7516035fed0edb5c6da50b8c07",
        "15cadac1e2a6aaa3c7d15246a1f37c56fbdd66787d1e66846e0f029a3d2c34e7",
        "362ea152ecb0d86affe1d673438797eb67a10b5f0479523f63692820936b5193",
        "32818902818006888dd33bf251cf1310507dbd0af41202304383fe904f5bfd85",
        "52936951716445cc9df76d660a06b025f8be7c9c8652467d64e639c35c3183a8",
        "e607d71b293f164a4eec1247561509f209358fb7cb2df85bde956d79557ab80f",
        "fd393c947fea0d1ffcf5354019a4d55e6e9acaad46728472c1bb142416bf25e1",
        "9e43694931b0",
    );

    /// The public modulus of the test key, for verifying our own signatures.
    const TEST_KEY_N_HEX: &str = concat!(
        // DER INTEGERs carry a leading 00 byte when the top bit is set;
        // ring wants the value itself, which for a 2048-bit key is 256 bytes.
        "a2bf269b48f86d86a0df534494b0e40685b18d3bb2d645d275916feaf69ffc",
        "54eb16e8219769c315b1a02c0002c259f8e3008169b38a3045f4f496ef3efbd6",
        "78dc352515f04d1d64c37be94c25992c239c8b5c2f568a34fc84cdbce0f055fe",
        "d42521ad9bb61e29d295beb22f47399bfaed4c365029d7a222e3e1803dd0b9f3",
        "c70ed8577872929b4f882ae2ffe30b3fdf71dd12a38c0df81de8b22f27f24d7f",
        "279d3a0389ecbfd5b6bb5b07b919243475e32044ce1f63e5a115d5a1790fb820",
        "5ed31a4c83b47a6b8598bdbf0360edb9e455b7e96fab0399a330bf65806d9729",
        "3efeb3d21e5e353b1eafe3bfaae54c6a3b9cb9aed16738c112157da2f65ca971",
        "57",
    );

    fn test_key_pair() -> RsaKeyPair {
        let der = hex::decode(TEST_KEY_PKCS1_DER_HEX).expect("test key hex decodes");
        let pkcs8 = pkcs1_to_pkcs8(&der);
        RsaKeyPair::from_pkcs8(&pkcs8).expect("test key parses as PKCS#8")
    }

    /// Build a PEM around the test key without writing the PEM header literally,
    /// so this file holds no string a secret scanner would flag.
    fn test_key_pem(label: &str, der: &[u8]) -> String {
        let begin = format!("-----BEGIN {label}-----");
        let end = format!("-----END {label}-----");
        let body = STANDARD.encode(der);
        let wrapped: Vec<String> = body
            .as_bytes()
            .chunks(64)
            .map(|chunk| String::from_utf8_lossy(chunk).into_owned())
            .collect();
        format!("{begin}\n{}\n{end}\n", wrapped.join("\n"))
    }

    #[test]
    fn pkcs1_wrapping_matches_the_canonical_pkcs8_encoding() {
        // Byte-identical to `openssl pkcs8 -topk8 -nocrypt` for the same key:
        // asserted by parsing the result, and by the fact that both PEM forms
        // sign to the same bytes in the test below.
        let der = hex::decode(TEST_KEY_PKCS1_DER_HEX).expect("hex");
        let wrapped = pkcs1_to_pkcs8(&der);
        assert!(wrapped.starts_with(&[0x30, 0x82]), "SEQUENCE, long form");
        assert!(
            RsaKeyPair::from_pkcs8(&wrapped).is_ok(),
            "wrapped key must parse as PKCS#8"
        );
    }

    #[test]
    fn parses_both_pem_forms_to_the_same_key() {
        let der = hex::decode(TEST_KEY_PKCS1_DER_HEX).expect("hex");
        let pkcs8 = pkcs1_to_pkcs8(&der);

        let from_pkcs1 = pkcs8_der_from_pem(&test_key_pem("RSA PRIVATE KEY", &der)).expect("pkcs1");
        let from_pkcs8 = pkcs8_der_from_pem(&test_key_pem("PRIVATE KEY", &pkcs8)).expect("pkcs8");

        assert_eq!(from_pkcs8, pkcs8, "PKCS#8 PEM decodes to its own DER");
        assert_eq!(from_pkcs1, pkcs8, "PKCS#1 PEM is wrapped to the same DER");
    }

    #[test]
    fn rejects_a_key_with_no_pem_block() {
        assert!(pkcs8_der_from_pem("not a key at all").is_err());
        assert!(pkcs8_der_from_pem("").is_err());
    }

    #[test]
    fn rejects_an_unsupported_key_type() {
        let der = hex::decode(TEST_KEY_PKCS1_DER_HEX).expect("hex");
        let pem = test_key_pem("ENCRYPTED PRIVATE KEY", &der);
        let error = pkcs8_der_from_pem(&pem).expect_err("must reject");
        assert!(
            error.to_string().contains("unsupported private key type"),
            "unexpected error: {error}"
        );
    }

    #[test]
    fn der_length_encodes_short_and_long_forms() {
        assert_eq!(der_len(0), vec![0x00]);
        assert_eq!(der_len(127), vec![0x7f]);
        assert_eq!(der_len(128), vec![0x81, 0x80]);
        assert_eq!(der_len(1190), vec![0x82, 0x04, 0xa6]);
    }

    #[test]
    fn jwt_has_the_shape_github_requires() {
        let key_pair = test_key_pair();
        let now = DateTime::parse_from_rfc3339("2026-09-19T12:00:00Z")
            .expect("timestamp")
            .with_timezone(&Utc);

        let jwt = sign_app_jwt(123456, &key_pair, now).expect("signs");
        let segments: Vec<&str> = jwt.split('.').collect();
        assert_eq!(segments.len(), 3, "header.payload.signature");

        let header: serde_json::Value = serde_json::from_slice(
            &URL_SAFE_NO_PAD
                .decode(segments[0])
                .expect("header is base64url"),
        )
        .expect("header is JSON");
        assert_eq!(header["alg"], "RS256");
        assert_eq!(header["typ"], "JWT");

        let claims: serde_json::Value = serde_json::from_slice(
            &URL_SAFE_NO_PAD
                .decode(segments[1])
                .expect("claims are base64url"),
        )
        .expect("claims are JSON");
        assert_eq!(claims["iss"], "123456");
        assert_eq!(claims["iat"], now.timestamp() - JWT_BACKDATE_SECS);
        assert_eq!(claims["exp"], now.timestamp() + JWT_LIFETIME_SECS);
        assert!(
            claims["exp"].as_i64().expect("exp is a number")
                - claims["iat"].as_i64().expect("iat is a number")
                <= 600,
            "GitHub rejects JWTs valid for more than ten minutes"
        );
    }

    #[test]
    fn jwt_signature_verifies_with_the_public_key() {
        // The real check on the signing path: verify our own signature with the
        // public half of the key. A wrong padding scheme or a corrupted
        // signature fails here.
        let key_pair = test_key_pair();
        let jwt = sign_app_jwt(42, &key_pair, Utc::now()).expect("signs");

        let (signing_input, signature) = jwt.rsplit_once('.').expect("three segments");
        let signature = URL_SAFE_NO_PAD
            .decode(signature)
            .expect("base64url signature");
        assert_eq!(signature.len(), 256, "2048-bit key signs to 256 bytes");

        let components = RsaPublicKeyComponents {
            n: hex::decode(TEST_KEY_N_HEX).expect("modulus hex"),
            e: vec![0x01, 0x00, 0x01], // 65537
        };
        components
            .verify(
                &RSA_PKCS1_2048_8192_SHA256,
                signing_input.as_bytes(),
                &signature,
            )
            .expect("signature must verify");
    }

    #[test]
    fn a_tampered_jwt_does_not_verify() {
        let key_pair = test_key_pair();
        let jwt = sign_app_jwt(42, &key_pair, Utc::now()).expect("signs");
        let (signing_input, signature) = jwt.rsplit_once('.').expect("three segments");
        let mut tampered = signing_input.to_string();
        tampered.push('x');

        let components = RsaPublicKeyComponents {
            n: hex::decode(TEST_KEY_N_HEX).expect("modulus hex"),
            e: vec![0x01, 0x00, 0x01],
        };
        let result = components.verify(
            &RSA_PKCS1_2048_8192_SHA256,
            tampered.as_bytes(),
            &URL_SAFE_NO_PAD.decode(signature).expect("signature"),
        );
        assert!(result.is_err(), "a tampered payload must not verify");
    }

    // ── HTTP flows, against a mock GitHub API ────────────────────────────────
    //
    // These exercise the two-step App handshake for real: sign a JWT, exchange
    // it for an installation token, cache it, refresh it when it ages out.

    use wiremock::matchers::{header_exists, method, path};
    use wiremock::{Mock, MockServer, ResponseTemplate};

    fn auth_for(server: &MockServer) -> AppAuth {
        let der = hex::decode(TEST_KEY_PKCS1_DER_HEX).expect("hex");
        let pem = test_key_pem("RSA PRIVATE KEY", &der);
        AppAuth::new(123456, &pem, &server.uri()).expect("app auth builds")
    }

    fn token_response(token: &str, expires_in_secs: i64) -> ResponseTemplate {
        ResponseTemplate::new(201).set_body_json(serde_json::json!({
            "token": token,
            "expires_at": (Utc::now() + ChronoDuration::seconds(expires_in_secs))
                .to_rfc3339(),
        }))
    }

    #[tokio::test]
    async fn exchanges_a_jwt_for_an_installation_token() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/app/installations/99/access_tokens"))
            .and(header_exists("authorization"))
            .respond_with(token_response("ghs_installation_token", 3600))
            .expect(1)
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        let token = auth.installation_token(99).await.expect("token");
        assert_eq!(token, "ghs_installation_token");
    }

    #[tokio::test]
    async fn the_jwt_sent_to_github_is_a_well_formed_app_jwt() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/app/installations/7/access_tokens"))
            .respond_with(token_response("ghs_abc", 3600))
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        auth.installation_token(7).await.expect("token");

        let requests = server.received_requests().await.expect("recorded requests");
        let header = requests[0]
            .headers
            .get("authorization")
            .expect("authorization header")
            .to_str()
            .expect("ascii");
        let jwt = header.strip_prefix("Bearer ").expect("bearer scheme");
        let segments: Vec<&str> = jwt.split('.').collect();
        assert_eq!(segments.len(), 3);

        let claims: serde_json::Value =
            serde_json::from_slice(&URL_SAFE_NO_PAD.decode(segments[1]).expect("claims decode"))
                .expect("claims are JSON");
        assert_eq!(claims["iss"], "123456", "issuer must be the App ID");
        assert!(claims["exp"].as_i64().expect("exp") > Utc::now().timestamp());
    }

    #[tokio::test]
    async fn installation_tokens_are_cached_not_refetched() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/app/installations/12/access_tokens"))
            .respond_with(token_response("ghs_cached", 3600))
            .expect(1) // exactly one request, however many times we call
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        let first = auth.installation_token(12).await.expect("first");
        let second = auth.installation_token(12).await.expect("second");
        assert_eq!(first, second);
        assert_eq!(first, "ghs_cached");
    }

    #[tokio::test]
    async fn a_token_near_expiry_is_refreshed() {
        let server = MockServer::start().await;
        // 60 seconds left is inside the 5-minute refresh margin, so the second
        // call must go back to the API rather than reuse it.
        Mock::given(method("POST"))
            .and(path("/app/installations/13/access_tokens"))
            .respond_with(token_response("ghs_soon_expired", 60))
            .expect(2)
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        auth.installation_token(13).await.expect("first");
        auth.installation_token(13).await.expect("second");
    }

    #[tokio::test]
    async fn a_token_for_a_different_installation_is_not_reused() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/app/installations/1/access_tokens"))
            .respond_with(token_response("ghs_one", 3600))
            .mount(&server)
            .await;
        Mock::given(method("POST"))
            .and(path("/app/installations/2/access_tokens"))
            .respond_with(token_response("ghs_two", 3600))
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        assert_eq!(auth.installation_token(1).await.expect("one"), "ghs_one");
        assert_eq!(auth.installation_token(2).await.expect("two"), "ghs_two");
    }

    #[tokio::test]
    async fn a_rejected_token_request_is_an_error_not_a_panic() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/app/installations/5/access_tokens"))
            .respond_with(ResponseTemplate::new(401).set_body_string("Bad credentials"))
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        let error = auth
            .installation_token(5)
            .await
            .expect_err("must fail")
            .to_string();
        assert!(error.contains("401"), "should name the status: {error}");
        assert!(
            !error.contains("ghs_"),
            "an error must never echo a credential: {error}"
        );
    }

    #[tokio::test]
    async fn finds_the_installation_for_a_repository() {
        let server = MockServer::start().await;
        Mock::given(method("GET"))
            .and(path("/repos/hyperpolymath/ubicity/installation"))
            .respond_with(ResponseTemplate::new(200).set_body_json(serde_json::json!({
                "id": 4242,
                "account": { "login": "hyperpolymath" }
            })))
            .expect(1)
            .mount(&server)
            .await;

        let auth = auth_for(&server);
        let id = auth
            .installation_for_repository("hyperpolymath", "ubicity")
            .await
            .expect("installation");
        assert_eq!(id, 4242);
    }
}
