#!/usr/bin/env bash
# SPDX-License-Identifier: PMPL-1.0-or-later
#
# fix-sast-workflow.sh — Auto-create CodeQL SAST workflow
#
# Category: StaticAnalysis
# Usage: fix-sast-workflow.sh <repo-path> <finding-json>
#
# Idempotent: exits 0 if a workflow already references codeql-action.
# Does NOT commit — dispatch-runner handles that.

set -euo pipefail

REPO_PATH="${1:?Usage: fix-sast-workflow.sh <repo-path> <finding-json>}"
FINDING_JSON="${2:?Usage: fix-sast-workflow.sh <repo-path> <finding-json>}"

WORKFLOWS_DIR="${REPO_PATH}/.github/workflows"

# --- Idempotency check ---
if [[ -d "${WORKFLOWS_DIR}" ]]; then
  if grep -rl 'codeql-action' "${WORKFLOWS_DIR}/" >/dev/null 2>&1; then
    echo "[fix-sast-workflow] CodeQL workflow already exists — skipping."
    exit 0
  fi
fi

# --- Detect languages for CodeQL matrix ---
declare -a LANGUAGES=()

# Check for JavaScript/TypeScript files
if find "${REPO_PATH}" -maxdepth 3 -name '*.js' -o -name '*.jsx' -o -name '*.ts' -o -name '*.tsx' -o -name '*.mjs' 2>/dev/null | grep -q .; then
  LANGUAGES+=("javascript-typescript")
fi

# Check for Python
if find "${REPO_PATH}" -maxdepth 3 -name '*.py' 2>/dev/null | grep -q .; then
  LANGUAGES+=("python")
fi

# Check for Go
if [[ -f "${REPO_PATH}/go.mod" ]]; then
  LANGUAGES+=("go")
fi

# Check for Java/Kotlin
if find "${REPO_PATH}" -maxdepth 3 -name '*.java' -o -name '*.kt' 2>/dev/null | grep -q .; then
  LANGUAGES+=("java-kotlin")
fi

# Check for Ruby
if find "${REPO_PATH}" -maxdepth 3 -name '*.rb' 2>/dev/null | grep -q .; then
  LANGUAGES+=("ruby")
fi

# Note: Rust is NOT supported by CodeQL — skip it.
# Default to 'actions' for workflow-only scanning if no language detected.
if [[ ${#LANGUAGES[@]} -eq 0 ]]; then
  LANGUAGES+=("actions")
fi

# --- Build the language matrix JSON array ---
LANG_MATRIX="["
for i in "${!LANGUAGES[@]}"; do
  if [[ $i -gt 0 ]]; then
    LANG_MATRIX+=", "
  fi
  LANG_MATRIX+="\"${LANGUAGES[$i]}\""
done
LANG_MATRIX+="]"

# --- Create workflows directory if needed ---
mkdir -p "${WORKFLOWS_DIR}"

# --- Generate codeql.yml ---
cat > "${WORKFLOWS_DIR}/codeql.yml" <<EOF
# SPDX-License-Identifier: PMPL-1.0-or-later
# Auto-generated by fix-sast-workflow.sh (gitbot-fleet)
name: "CodeQL"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1'

permissions: read-all

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ${LANG_MATRIX}

    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@6624720a57d4c312633c7b953db2f2da5bcb4c3a # v3
        with:
          languages: \${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@6624720a57d4c312633c7b953db2f2da5bcb4c3a # v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@6624720a57d4c312633c7b953db2f2da5bcb4c3a # v3
        with:
          category: "/language:\${{ matrix.language }}"
EOF

echo "[fix-sast-workflow] Created .github/workflows/codeql.yml with languages: ${LANGUAGES[*]}"
