// SPDX-License-Identifier: PMPL-1.0-or-later
//! Git hook management

use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::PathBuf;
use tracing::info;

use crate::error::{Error, Result};

/// Hook types supported
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HookType {
    PreCommit,
    PrePush,
    CommitMsg,
    PostCommit,
    PostCheckout,
    PostMerge,
}

impl HookType {
    /// Get the filename for this hook type
    pub fn filename(&self) -> &'static str {
        match self {
            HookType::PreCommit => "pre-commit",
            HookType::PrePush => "pre-push",
            HookType::CommitMsg => "commit-msg",
            HookType::PostCommit => "post-commit",
            HookType::PostCheckout => "post-checkout",
            HookType::PostMerge => "post-merge",
        }
    }
}

/// Hook manager for a repository
pub struct HookManager {
    /// Root path of the managed repository
    #[allow(dead_code)]
    repo_path: PathBuf,
    /// Path to the .git/hooks directory
    hooks_dir: PathBuf,
}

impl HookManager {
    /// Create a new hook manager for a repository
    pub fn new(repo_path: PathBuf) -> Result<Self> {
        let hooks_dir = repo_path.join(".git/hooks");
        if !hooks_dir.exists() {
            return Err(Error::Hook(format!(
                "Git hooks directory not found: {}",
                hooks_dir.display()
            )));
        }

        Ok(HookManager {
            repo_path,
            hooks_dir,
        })
    }

    /// Check if a hook exists
    pub fn hook_exists(&self, hook_type: HookType) -> bool {
        self.hooks_dir.join(hook_type.filename()).exists()
    }

    /// Get the path to a hook
    pub fn hook_path(&self, hook_type: HookType) -> PathBuf {
        self.hooks_dir.join(hook_type.filename())
    }

    /// Install a hook from content
    pub fn install_hook(&self, hook_type: HookType, content: &str) -> Result<()> {
        let hook_path = self.hook_path(hook_type);

        // Backup existing hook if it exists
        if hook_path.exists() {
            let backup_path = hook_path.with_extension("backup");
            fs::rename(&hook_path, &backup_path)?;
            info!(
                "Backed up existing {} hook to {}",
                hook_type.filename(),
                backup_path.display()
            );
        }

        // Write the new hook
        fs::write(&hook_path, content)?;

        // Make it executable
        let mut perms = fs::metadata(&hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&hook_path, perms)?;

        info!("Installed {} hook", hook_type.filename());
        Ok(())
    }

    /// Remove a hook
    pub fn remove_hook(&self, hook_type: HookType) -> Result<()> {
        let hook_path = self.hook_path(hook_type);

        if hook_path.exists() {
            fs::remove_file(&hook_path)?;
            info!("Removed {} hook", hook_type.filename());
        }

        // Restore backup if it exists
        let backup_path = hook_path.with_extension("backup");
        if backup_path.exists() {
            fs::rename(&backup_path, &hook_path)?;
            info!("Restored backup {} hook", hook_type.filename());
        }

        Ok(())
    }

    /// Generate pre-commit hook content
    pub fn generate_pre_commit_hook(rulesets: &[String]) -> String {
        let rulesets_arg = rulesets.join(",");
        format!(
            r#"#!/bin/bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by robot-repo-automaton
# Rulesets: {rulesets}

set -e

# Check if robot-repo-automaton is available
if ! command -v robot-repo-automaton &> /dev/null; then
    echo "Warning: robot-repo-automaton not found, skipping pre-commit checks"
    exit 0
fi

# Run pre-commit checks
robot-repo-automaton hooks pre-commit \
    --rulesets "{rulesets_arg}" \
    --fail-on-error

exit $?
"#,
            rulesets = rulesets_arg,
            rulesets_arg = rulesets_arg
        )
    }

    /// Generate pre-push hook content
    pub fn generate_pre_push_hook(rulesets: &[String]) -> String {
        let rulesets_arg = rulesets.join(",");
        format!(
            r#"#!/bin/bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by robot-repo-automaton
# Rulesets: {rulesets}

set -e

# Check if robot-repo-automaton is available
if ! command -v robot-repo-automaton &> /dev/null; then
    echo "Warning: robot-repo-automaton not found, skipping pre-push checks"
    exit 0
fi

# Get the remote and URL
remote="$1"
url="$2"

# Run pre-push checks
robot-repo-automaton hooks pre-push \
    --rulesets "{rulesets_arg}" \
    --remote "$remote" \
    --verify-signatures

exit $?
"#,
            rulesets = rulesets_arg,
            rulesets_arg = rulesets_arg
        )
    }

    /// Generate commit-msg hook for conventional commits
    pub fn generate_commit_msg_hook() -> String {
        r#"#!/bin/bash
# SPDX-License-Identifier: PMPL-1.0-or-later
# Generated by robot-repo-automaton
# Enforces conventional commit format

set -e

commit_msg_file="$1"
commit_msg=$(cat "$commit_msg_file")

# Conventional commit pattern
pattern="^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\(.+\))?: .+"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
    echo "Error: Commit message does not follow conventional commit format"
    echo "Expected: <type>(<scope>): <description>"
    echo "Types: feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert"
    echo ""
    echo "Your message: $commit_msg"
    exit 1
fi

exit 0
"#.to_string()
    }

    /// Install standard hooks for cicd-hyper-a integration
    pub fn install_standard_hooks(&self, rulesets: &[String]) -> Result<()> {
        // Pre-commit hook
        let pre_commit = Self::generate_pre_commit_hook(rulesets);
        self.install_hook(HookType::PreCommit, &pre_commit)?;

        // Pre-push hook
        let pre_push = Self::generate_pre_push_hook(rulesets);
        self.install_hook(HookType::PrePush, &pre_push)?;

        // Commit-msg hook
        let commit_msg = Self::generate_commit_msg_hook();
        self.install_hook(HookType::CommitMsg, &commit_msg)?;

        info!("Installed standard hooks for cicd-hyper-a integration");
        Ok(())
    }
}

/// Pre-commit check runner
pub struct PreCommitChecker {
    repo_path: PathBuf,
}

impl PreCommitChecker {
    pub fn new(repo_path: PathBuf) -> Self {
        PreCommitChecker { repo_path }
    }

    /// Run RSR compliance checks
    pub fn check_rsr_compliance(&self) -> Result<Vec<String>> {
        let mut violations = Vec::new();

        // Check for banned file types
        let banned_extensions = ["ts", "go", "py"];
        for ext in &banned_extensions {
            let pattern = format!("**/*.{}", ext);
            let matches: Vec<_> = glob::glob(&self.repo_path.join(&pattern).to_string_lossy())
                .map_err(|e| Error::Detection(e.to_string()))?
                .filter_map(|r| r.ok())
                .collect();

            if !matches.is_empty() {
                violations.push(format!(
                    "RSR violation: Found {} banned .{} files",
                    matches.len(),
                    ext
                ));
            }
        }

        // Check for required files
        let required_files = [
            "README.adoc",
            "LICENSE",
            "SECURITY.md",
            ".github/workflows/codeql.yml",
        ];

        for file in &required_files {
            if !self.repo_path.join(file).exists() {
                // Check alternative README
                if *file == "README.adoc" && self.repo_path.join("README.md").exists() {
                    continue;
                }
                violations.push(format!("RSR violation: Missing required file {}", file));
            }
        }

        Ok(violations)
    }

    /// Check for secrets in staged files
    pub fn check_secrets(&self) -> Result<Vec<String>> {
        let findings = Vec::new();

        // Simple pattern matching for common secret patterns
        let _secret_patterns = [
            r#"(?i)api[_-]?key\s*[:=]\s*["'][^"']+["']"#,
            r#"(?i)secret[_-]?key\s*[:=]\s*["'][^"']+["']"#,
            r#"(?i)password\s*[:=]\s*["'][^"']+["']"#,
            r"ghp_[a-zA-Z0-9]{36}",  // GitHub PAT
            r"github_pat_[a-zA-Z0-9]{22}_[a-zA-Z0-9]{59}",  // Fine-grained PAT
            r"sk-[a-zA-Z0-9]{48}",   // OpenAI key
        ];

        // This would scan staged files for secret patterns
        // Simplified implementation - would use regex in real version

        Ok(findings)
    }

    /// Check SPDX headers
    pub fn check_spdx_headers(&self) -> Result<Vec<String>> {
        let mut missing = Vec::new();

        // Check source files for SPDX headers
        let source_extensions = ["rs", "hs", "js", "ts", "py", "go", "yml", "yaml"];

        for ext in &source_extensions {
            let pattern = format!("{}/**/*.{}", self.repo_path.display(), ext);
            if let Ok(paths) = glob::glob(&pattern) {
                for path in paths.filter_map(|r| r.ok()) {
                    // Skip generated and vendor directories
                    let path_str = path.to_string_lossy();
                    if path_str.contains("/target/")
                        || path_str.contains("/node_modules/")
                        || path_str.contains("/vendor/")
                    {
                        continue;
                    }

                    if let Ok(content) = fs::read_to_string(&path) {
                        if !content.contains("SPDX-License-Identifier") {
                            missing.push(format!(
                                "Missing SPDX header: {}",
                                path.display()
                            ));
                        }
                    }
                }
            }
        }

        Ok(missing)
    }
}
